{% set name = "metatrain" %}
{% set version = "2025.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metatrain-{{ version }}.tar.gz
  sha256: 36a073e25421cae46b8c567d27a8e953f9d64afa92c2ce6ad9dcaaacf5c95c48

build:
  entry_points:
    - mtt = metatrain.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - ase
    - python-metatensor-learn ==0.3.1
    - python-metatensor-operations ==0.3.2
    - python-metatensor-torch ==0.7.5
    - jsonschema
    - omegaconf
    - python-hostlist
    - pytorch
    - python-vesin

test:
  imports:
    - metatrain
  commands:
    - pip check
    - mtt --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/metatensor/metatrain
  summary: Training and evaluating machine learning models for atomistic systems.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://metatensor.github.io/metatrain

extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
