{% set name = "metatrain" %}
{% set version = "2025.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metatrain-{{ version }}.tar.gz
  sha256: 75b2a630f049f0a95945ba2656a7120d4eabe7582f9ac059d7373cb97aba92b6

build:
  entry_points:
    - mtt = metatrain.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  ignore_run_exports:
    - pytorch *  # pytorch is only used as a Python package

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - ase
    - python-metatensor-learn >=0.3.2,<0.4
    - python-metatensor-operations >=0.3.3,<0.4
    - python-metatensor-torch >=0.7.6,<0.8
    - python-metatomic-torch >=0.1.2,<0.2
    - jsonschema
    - omegaconf
    - python-hostlist
    - pytorch
    - python-vesin

test:
  imports:
    - metatrain
  commands:
    - pip check
    - mtt --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/metatensor/metatrain
  summary: Training and evaluating machine learning models for atomistic systems.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://metatensor.github.io/metatrain

extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
